INSERT INTO torneos (nombre, deporte, fecha, ubicacion, descripcion, cupo, precio, estado) VALUES
('Campeonato Nacional de Natación', 'natación', '2025-04-14', 'Centro Acuático Olímpico', 'El Campeonato Nacional de Natación es el evento cumbre de la natación en el país. Atrae a los mejores nadadores de todas las categorías, desde juveniles hasta adultos. Las competencias incluyen pruebas de estilo libre, espalda, pecho y mariposa, así como relevos. ¡No te pierdas la oportunidad de presenciar la emoción de la natación de alto nivel!', 250, 80.00, 'activo'),
('Travesía Lago de Chapala', 'aguas abiertas', '2025-05-19', 'Lago de Chapala, Jalisco', 'La Travesía Lago de Chapala es una competencia de aguas abiertas que desafía a los nadadores a recorrer una distancia de 10 kilómetros en el hermoso Lago de Chapala. El evento es conocido por sus impresionantes paisajes y su ambiente festivo. ¡Únete a cientos de nadadores y disfruta de una experiencia inolvidable!', 300, 120.00, 'activo'),
('Triatlón Acapulco', 'triatlón', '2025-06-09', 'Playa Icacos, Acapulco', 'El Triatlón Acapulco es un evento de resistencia que combina natación, ciclismo y carrera a pie. Los participantes deberán completar un recorrido desafiante a través de la hermosa bahía de Acapulco y sus alrededores. ¡Prepárate para poner a prueba tus límites y disfrutar de un ambiente espectacular!', 400, 150.00, 'activo'),
('Acuatlón Ciudad de México', 'acuatlón', '2025-07-04', 'Parque Bicentenario, CDMX', 'El Acuatlón Ciudad de México es una competencia que combina carrera a pie y natación. Los participantes deberán completar un recorrido de 5 kilómetros de carrera, seguidos de 1 kilómetro de natación en el Parque Bicentenario. ¡Un evento ideal para aquellos que buscan un desafío de resistencia en un entorno urbano!', 200, 60.00, 'activo'),
('Maratón de la Ciudad', 'atletismo', '2025-08-11', 'Paseo de la Reforma, CDMX', 'El Maratón de la Ciudad es uno de los eventos de atletismo más importantes de México. Atrae a miles de corredores de todo el mundo, quienes recorren los 42.195 kilómetros a través de los lugares más emblemáticos de la Ciudad de México. ¡Únete a la fiesta del running y vive la emoción de cruzar la meta!', 1000, 50.00, 'activo'),
('Copa de Natación Juvenil', 'natación', '2025-09-17', 'Alberca Olímpica Francisco Márquez', 'La Copa de Natación Juvenil es un evento dedicado a los jóvenes talentos de la natación mexicana. Las competencias incluyen pruebas de todos los estilos y distancias, y sirven como plataforma para que los jóvenes nadadores muestren su potencial. ¡Apoya a las futuras estrellas de la natación nacional!', 150, 30.00, 'activo'),
('Desafío de Aguas Abiertas Cancún', 'aguas abiertas', '2025-10-24', 'Playa Delfines, Cancún', 'El Desafío de Aguas Abiertas Cancún es una competencia que ofrece diferentes distancias para nadadores de todos los niveles, desde principiantes hasta expertos. Los participantes podrán disfrutar de las cristalinas aguas del Caribe y de los hermosos paisajes de Cancún. ¡Una experiencia única para los amantes de la natación en aguas abiertas!', 350, 130.00, 'activo'),
('Triatlón Valle de Bravo', 'triatlón', '2025-11-07', 'Presa Valle de Bravo, Estado de México', 'El Triatlón Valle de Bravo es un evento que combina natación, ciclismo y carrera a pie en un entorno natural impresionante. Los participantes deberán completar un recorrido desafiante a través de la Presa Valle de Bravo y sus alrededores. ¡Un evento ideal para aquellos que buscan un triatlón exigente en un lugar espectacular!', 300, 140.00, 'activo');





INSERT INTO testimonios (comentario, calificacion, usuarioId) VALUES
('¡Gran experiencia en el torneo! La organización fue excelente y la competencia de alto nivel. Definitivamente volveré el próximo año.', 5, 1), -- Asumiendo que Juan Pérez tiene usuarioId 1
('Mi primera vez en una competencia de aguas abiertas y me encantó. Los organizadores fueron muy atentos y el recorrido estaba bien señalizado.', 5, 1), -- Asumiendo que María Rodríguez tiene usuarioId 2
('El triatlón estuvo bien organizado, aunque hubo algunos problemas con la señalización en la ruta de ciclismo. Por lo demás, todo excelente.', 4, 1), -- Asumiendo que Carlos Sánchez tiene usuarioId 3
('Increíble ambiente en el maratón. Los puntos de hidratación estaban bien distribuidos y el apoyo del público fue motivador.', 5, 1), -- Asumiendo que Ana López tiene usuarioId 4
('Participé en el acuatlón y fue una experiencia única. Las transiciones estaban bien organizadas y el personal muy amable.', 5, 1), -- Asumiendo que Roberto Gómez tiene usuarioId 5
('Excelente organización en el campeonato de natación. Las instalaciones estaban impecables y el cronometraje fue muy preciso.', 5, 1), -- Asumiendo que Laura Martínez tiene usuarioId 6
('Participé en la travesía del lago y fue una experiencia desafiante pero muy gratificante. El apoyo de los kayaks de seguridad fue fundamental.', 5, 1), -- Asumiendo que Miguel Ángel Torres tiene usuarioId 7
('El triatlón de montaña fue muy exigente pero la organización estuvo a la altura. Los avituallamientos estaban bien surtidos y el recorrido perfectamente marcado.', 4, 2), -- Asumiendo que Patricia Jiménez tiene usuarioId 8
('Mi primera competencia de natación y quedé muy satisfecho. El ambiente fue muy amigable para principiantes y los jueces muy profesionales.', 5, 2); -- Asumiendo que Daniel Ortiz tiene usuarioId 9